name: Build App Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Release Apk
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'oracle'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --build-name=1.0.0 --build-number=1

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Releases
          path: build/app/outputs/flutter-apk/app-release.apk
