name: Build App Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Release Apk
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '18'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --build-name=1.0.0 --build-number=1

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: build/app/outputs/flutter-apk/app-release.apk
